apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-1
  name: demo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-1
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-1
    spec:
      containers:
        - image: halfcoconut/hello-egg:in-cluster-v1
          name: demo-1
          imagePullPolicy: Always
status: {}
