apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-world-flask
spec:
  interval: 5s
  ref:
    branch: main
#    替换成 repo 地址
  url: https://github.com/<repo-address>/fluxcd-demo